# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Publish And Deploy Demo

on:
  push:
    #branches: [ "main" ]
    tags:
      - "v*"

jobs:
  # 任务名称
  Publish And Deploy Demo:
    runs-on: ubuntu-latest
    steps:
    # 下载源码
    - name: checkout
      uses: actions/checkout@v2
    # 打包构建
    - name: Build
      uses: actions/setup-node@v3
    - run: npm install
    - run: npm run build
    - run: tar -zcvf release.tgz dist
    
    # 发布 Release
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
      
    # 上传构建结果到 Release
    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./release.tgz
        asset_name: release.tgz
        asset_content_type: application/x-tgz
        
    # 登录 - 部署到服务器
    - name: Deploy
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        port: ${{ secrets.PORT }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: |
          cd /usr/share/nginx/html/github
          wget https://github.com/szjSmiling/github-actions/releases/latest/download/release.tgz -O release.tgz
          tar zxvf release.tgz
          
    
        
    
    
    
    
    
    
